### ISSUE TITLE
Enable user last login time in user table

### ISSUE THREAD

**Issue by zhouhao** [SaltyNote/saltynote-service#39]
This will be helpful, if we want to do db optimization or cleanup in the future.

If user has not been login again in the past 2 years, maybe we can mark user as unactive. 

We can send reminder to users, if no response, then we can start to do some db optimization.

This is not a prblem in a short, but we can enable this field first.

**Comment by gaomc66** [comment]
Hi! Can I work on this issue? I can add lastlogin_time column in user table and update it when user login.

**Comment by zhouhao** [comment]
Thank you! Sure!

For DB schema change, you can add a migration script [here](https://github.com/SaltyNote/saltynote-service/tree/master/src/main/resources/db/migration) to add `last_login_time`.

The login query is here: https://github.com/SaltyNote/saltynote-service/blob/master/src/main/java/com/saltynote/service/service/UserDetailsServiceImpl.java#L21

Please feel free to let me know if you need more details.
Cheers

**Comment by zhouhao** [comment]
Thank you so much!
