### ISSUE TITLE
Enable notes tag support

### ISSUE THREAD

**Issue by zhouhao** [SaltyNote/saltynote-service#43]
[Note.java](https://github.com/SaltyNote/saltynote-service/blob/master/src/main/java/com/saltynote/service/entity/Note.java) does not have tags field yet.

This should be a very helpful attribute, and it can help users to organize their notes much more efficient.

We can have the tag as a string field, and each tag is separated by a comma.

**Comment by lodye509** [comment]
hi Zhouhao, I'm new to spring boot and like to take one of the open request. Do you think this is a good request for me to start with? I'm still going over the code, and thinking it could help me to understand the whole structure by working on something real.

**Comment by zhouhao** [comment]
Thank you! @lodye509 , yeah, practice will make you understand spring boot faster.
This can be a good start, I will give you more details soon.

**Comment by lodye509** [comment]
Thank you ;)

**Comment by zhouhao** [comment]
### Step 1: add new `tags` field for note table, and update Note entity class.
1. Add `V0_0_9__add_tags_to_note_table.sql` into [`db/migration`](https://github.com/SaltyNote/saltynote-service/tree/master/src/main/resources/db/migration)
I use Flyway for db migration, and you can find more details about it [here:`SQL-based migrations`](https://flywaydb.org/documentation/concepts/migrations#sql-based-migrations).
2. Add a new string field named `tags` in [Node.java](https://github.com/SaltyNote/saltynote-service/blob/master/src/main/java/com/saltynote/service/entity/Note.java) 

Benefits of db migration: no need to patch it manually, easy to keep it consistent.

**Comment by zhouhao** [comment]
Note: make it `nullable` should be good enough, as `tags` is an optional attribute of a note.

**Comment by zhouhao** [comment]
Then it should be all set. We enabled `tags` support for note now.

### What's next: update the unit test

1. Set tags in [`public static Note createTmpNote(String userId)`](https://github.com/SaltyNote/saltynote-service/blob/master/src/test/java/com/saltynote/service/controller/NoteControllerTest.java#L73)
2. It will be great if you can follow [`updateNoteByIdShouldSuccess()`](https://github.com/SaltyNote/saltynote-service/blob/master/src/test/java/com/saltynote/service/controller/NoteControllerTest.java#L170) and add a dedicated test for tags update.

**Comment by zhouhao** [comment]
Hi @lodye509, this should be the changes that we need to take for service side.
And please feel free to let me know if you need more information.

Maybe it is confusing to you, and I will come up with more issues. 
I believe you will be more conformable soon.

**Comment by lodye509** [comment]
@zhouhao thanks for the details~ Yea I didn’t use flyway before, so might need to take a while to start. But no worries I think I can figure this out xD

**Comment by lodye509** [comment]
> ### Step 1: add new `tags` field for note table, and update Note entity class.
> 1. Add `V0_0_9__add_tags_to_note_table.sql` into [`db/migration`](https://github.com/SaltyNote/saltynote-service/tree/master/src/main/resources/db/migration)
>    I use Flyway for db migration, and you can find more details about it [here:`SQL-based migrations`](https://flywaydb.org/documentation/concepts/migrations#sql-based-migrations).
> 2. Add a new string field named `tags` in [Node.java](https://github.com/SaltyNote/saltynote-service/blob/master/src/main/java/com/saltynote/service/entity/Note.java)
> 
> Benefits of db migration: no need to patch it manually, easy to keep it consistent.

@zhouhao For the new field tags, what's the reasonable maximum length for it? I will say something around 20 since we have text field. What do you think?

**Comment by zhouhao** [comment]
We can make it larger. People may add multiple tags. How about 128?

**Comment by lodye509** [comment]
Just checked the tags in instagram lol and seems like most of the self-define tags are between 10 to 15 per one. So 64 is about 4 to 5 tags and 128 is 9ish. I think we can go with 128 for now.

**Comment by zhouhao** [comment]
Thank you for your investigation. ;-)

**Comment by zhouhao** [comment]
BTW: there is a repo called `xxx-starter` in this org, which could be helpful for you, if you haven't check it out. ;-)

**Comment by lodye509** [comment]
Nice! Thank you, what’s this repo actually for?

**Comment by zhouhao** [comment]
It is used for setting up private configuration for development environment (for internal developers).

**Comment by zhouhao** [comment]
hello, is everything going ok so far? Just want to check whether anything I can help. No rush, no pressure.

**Comment by lodye509** [comment]
hey thank you for asking xD I was stuck on docker a little, but resolved issue now. But I do have a question on mariaDB, so you have mentioned the db change will be patched automatically, but I’m not able to see the changes. Do you have any clue what I have missed?

**Comment by zhouhao** [comment]
Thank you for your fast response.
Did you tried to start database with docker as below:
```bash
cd YOUR_PATH/saltynote-service

# This will start the database
docker-compose up
```

**Comment by lodye509** [comment]
Yes I have, and also added one property to enable the history table.

**Comment by zhouhao** [comment]
Sorry, what do you mean about `added one property to enable the history table`?
Basically, there is no need to manually touch the database, schema change will be patched by flyway too, even the history table.

**Comment by lodye509** [comment]
My bad, I added a parameter to the properties file which can enable the flyway history table. I got error saying this without the parameter.

**Comment by zhouhao** [comment]
Interesting. Can you also share the error? Maybe I can take a look, and document it in case other people may also see this error.

**Comment by lodye509** [comment]
Sure, org.flywaydb.core.api.FlywayException: Found non-empty schema(s) without schema history table! Use baseline() or set baselineOnMigrate to true to initialize the schema history table.

**Comment by zhouhao** [comment]
Thank you!

Interesting. Does this mean that you already have some tables in that database before starting this spring boot service?

**Comment by lodye509** [comment]
Code changes done and merged to master branch.
