### ISSUE TITLE
last_login_time follow up

### ISSUE THREAD

**Issue by zhouhao** [SaltyNote/saltynote-service#55]
Thanks for @gaomc66 to enable last login time feature in #39

However, since I provided the "wrong" information, we have last login time updated at the wrong place.

The correct place should be: `successfulAuthentication(...)`
https://github.com/SaltyNote/saltynote-service/blob/master/src/main/java/com/saltynote/service/security/JWTAuthenticationFilter.java#L55

We should only update last login time after user logs in sucessfully.

Sorry for the the wrong information I provded in #39 .

**Comment by zhouhao** [comment]
This may worth further discussion.

When to log the last login time?
1. When user tries to login (no matter succeeds or fails)
2. Only  for succeeding

**Comment by gaomc66** [comment]
Yea you are right! This way is more make sense, We should record login time only for succeeding only! I can fix this. 😃
